name: studio
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  provider: any

dev_dependencies:
  pedantic: ^1.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/OpenSans-Regular.ttf